  language: python
  python:
    - "3.6"
  install:
    - pip install -r requirements.txt
  services:
    - docker
  before_install:
    - docker-compose -f ./tests/act2_test/docker-compose.yml up -d
    - docker-compose -f ./tests/final_test/docker-compose.yml up -d
  before_script:
    - sleep 30
  script:
    - python ./tests/test_webserver.py
    #- python ./tests/test_upload.py
    - pytest tests/test_all.py
