  language: python
  python:
    - "2.7"
    - "3.7"
  install:
    - pip install -r requirements.txt
  services:
    - docker
  before_install:
    - docker-compose -f act2_test/docker-compose.yml up -d
  script:
    - pytest
