  language: python
  python:
    - "3.5.2"
  install:
    - pip install -r requirements.txt
  services:
    - docker
  before_install:
    - docker-compose -f ./tests/act2_test/docker-compose.yml up -d
    - docker-compose -f ./tests/act4_test/docker-compose.yml up -d
  script:
    - python ./tests/test_webserver.py
    #- python ./tests/test_upload.py
    - pytest tests/test_upload.py
