  language: python
  python:
    - "2.7"
  install:
    - pip install -r requirements.txt
  services:
    - docker
  before_install:
    - docker-compose -f ./tests/act2_test/docker-compose.yml up -d
    - docker-compose -f ./tests/act3_test/docker-compose.yml up -d
  script:
    - python ./tests/test_webserver.py
    - python ./tests/test_authentication.py
