version: "2"
services:
  webserver:
   build: ./app
   ports:
      - "5000:5000"
   links:
      - db
   depends_on:
      - db
  db:
    build: ./db
    ports:
      - "32000:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
